### ISSUE TITLE
http://useraccounts-ratchet.meteor.com doesn't seem to exist

### ISSUE THREAD

**Issue by FickleLife** [meteor-useraccounts/ratchet#1]
Am getting an error at http://useraccounts-ratchet.meteor.com "This site is under construction. Come back later please ;-)" - I have been several times so I don't think it's meteor.com lazy load...

**Comment by splendido** [comment]
You're right!
It was me putting the message "This site is under construction. Come back later please ;-)".

The thing is we still miss a [boilerplate](https://github.com/meteor-useraccounts/boilerplates) for ratchet... :-(

Would you be willing to create it?
In case, just start off from one of the others and make a PR to add it to the repo.

That would be much appreciated!

Thanks,
Luca

**Comment by splendido** [comment]
deployed!
